---
title: "metadata_merge"
author: "Alma Garcia"
date: "2024-02-17"
output: html_document
---

# manifest and metadata cleanup

Import libraries
```{r}
library(tidyverse)
```

## manifest
Import old manifest files:
```{r}
mouse_manifest_old <- read.delim("mouse_starch_manifest.tsv")
human_manifest_old <- read.delim("starch_manifest.txt")
```

Import metadata files:
```{r}
mouse_metadata <- read.delim("metadata/mouse_metadata.tsv")
human_metadata <- read.delim("metadata/human_metadata.tsv")
```

Filter manifest table to only include samples in metadata files:
```{r}
mouse_manifest <- mouse_manifest_old %>% filter(sample.id %in% mouse_metadata$sample_id)
human_manifest <- human_manifest_old %>% filter(sample.id %in% human_metadata$sample_id)
```

Export new manifest files:
```{r}
write_delim(mouse_manifest, "mouse_manifest.tsv", delim = "\t")
write_delim(human_manifest, "human_manifest.tsv", delim = "\t")
```

## metadata table

Add cohort columns
```{r}
human_metadata <- human_metadata %>% mutate(cohort = "human")
mouse_metadata <- mouse_metadata %>% mutate(cohort = "mouse")
```

Merge tables and cleanup:
```{r}
metadata <- full_join(human_metadata, mouse_metadata) %>%
	# drop unused columns
	select(-c(timepoint, sample_type)) %>%
	# rename Treatment to starch_type
	rename(starch_type = Treatment,
				 `sample-id` = sample_id) %>%
	# create treatment group column (organism-treatment)
	mutate(group = str_c(cohort, trt, sep = "-"))
```

Export merged metadata:
```{r}
write_tsv(metadata, "metadata/metadata.tsv")
```

